default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: cursor_ishop_development
  username: ishop_app
  password: 'Pa$$w0rd'

production:
  <<: *default
  database: cursor_ishop_production
  username: ishop_app
  password: 'Pa$$w0rd'

test:
  <<: *default
  database: cursor_ishop_test
  username: ishop_app
  password: 'Pa$$w0rd'